version: '3'

dotenv:
  - .env

tasks:

  setup:
    dir: packages/waitlist
    cmds:
    - npm install

  login:
    - echo "Password is $NUV_PASSWORD"
    - nuv -login $NUV_HOST $NUV_USER

  default:
    - task: build
    - task: deploy

  build:
    dir: packages/waitlist
    cmds:
    - tsc

  deploy:
    dir: packages
    cmds: 
    - nuv -wsk project deploy
